/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "zgbjccnphtibqpfqzjww"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpnYmpjY25waHRpYnFwZnF6and3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjY5MzE4MjksImV4cCI6MjA4MjUwNzgyOX0.DfPFqpm-gNtx36ncZ-4ePNzdovYlXYEUvbmToW_WTmY"